targets:
  $default:
    builders:
      freezed:
        enabled: true

      retrofit_generator|retrofit_generator:
        enabled: true

      auto_route_generator|auto_route_generator:
        enabled: true

      source_gen|combining_builder:
        options:
          ignore_for_file:
            - literal_only_boolean_expressions
            - unnecessary_non_null_assertion
            - unnecessary_string_interpolations