name: waslship
description: WaslShip Flutter Application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Navigation
  auto_route: ^10.2.0

  # Networking
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  internet_connection_checker_plus: ^2.7.2

  # State Management
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0

  # Images
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

  # UI
  skeletonizer: ^2.1.0+1
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1

  # Environment
  flutter_dotenv: ^6.0.0

  # Utilities
  logger: ^2.6.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  easy_localization: ^3.0.8

  flutter_native_splash: ^2.4.6
  equatable: ^2.1.0
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.5.4

  freezed: ^3.2.3

  json_serializable: ^6.11.1

  retrofit_generator: ^10.0.1

  auto_route_generator: ^10.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/translations/