name: waslship
description: A Flutter application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Navigation
  auto_route: ^10.2.0

  # Networking
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  internet_connection_checker_plus: ^2.7.2

  # State Management
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  equatable: ^2.0.7
  fpdart: ^1.1.1

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0

  # Images
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0

  # UI
  skeletonizer: ^2.1.0+1
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1

  # Environment
  flutter_dotenv: ^6.0.0

  # Utils
  logger: ^2.6.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  easy_localization: ^3.0.8

  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.5.4
  auto_route_generator: ^10.0.1
  retrofit_generator: ^10.0.2
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/translations/